language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - gem update --system
  - gem install compass
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
notifications:
  email:
    - pokeplus@gmail.com
    - chaosillu@gmail.com
    - difgrt@gmail.com
